using System.Globalization;
using DoraSaver.Core;

namespace DoraSaver.Setup;

/// <summary>Installer text in Chinese, Japanese and English.</summary>
internal sealed record SetupText(
    UiLanguage Language,
    string FontName,
    string Title,
    string Intro,
    string SaversLabel,
    string NamesLabel,
    string Install,
    string Uninstall,
    string OpenSettings,
    string Close,
    string Cancel,
    string Fetching,
    string Verified,
    string Reused,
    string Failed,
    string NeedsUnar,
    string MovieNotFound,
    string Installing,
    string InstalledFiles,
    string BackedUp,
    string Done,
    string DoneWithFailures,
    string NothingInstalled,
    string ActiveChanged,
    string InstallingWebView2,
    string WebView2NotTrusted,
    string WebView2Failed,
    string Uninstalling,
    string UninstallDone,
    string ConfirmUninstall,
    string PickSomething,
    string Warning,
    string UninstallLeftovers,
    string AlreadyRunning,
    string Error)
{
    public static SetupText Chinese { get; } = new(
        UiLanguage.Chinese,
        "Microsoft YaHei UI",
        "哆啦A梦屏保复活计划 安装程序",
        "本程序会从互联网档案馆（Wayback Machine）下载哆啦A梦官方网站当年免费发布的屏保原始文件，在你的电脑上提取出动画，再用开源 Flash 模拟器 Ruffle 播放。本程序不包含任何哆啦A梦素材；动画版权归 © 藤子プロ・小学館 等所有，仅供个人欣赏。",
        "要安装的屏保",
        "屏保列表中显示的名字",
        "安装",
        "卸载",
        "打开屏保设置",
        "关闭",
        "取消",
        "正在获取：{0}（{1}）",
        "  ✓ 已下载并通过校验",
        "  ✓ 已沿用之前安装的文件（校验一致）",
        "  ✗ 失败：{0}",
        "  这个屏保的原始文件格式较老，需要额外下载开源解压工具 unar（The Unarchiver）。",
        "在原始文件中没有找到和记录一致的动画。",
        "正在安装……",
        "已安装 {0} 个屏保文件。",
        "已把损坏的旧版屏保移到备份文件夹：{0}",
        "安装完成！共 {0} 个屏保。打开「屏幕保护程序设置」就能选择。",
        "安装完成 {0} 个屏保，以下 {1} 个没能安装：{2}",
        "没有安装任何屏保。",
        "当前使用的屏保已改为新版：{0}",
        "需要 Microsoft Edge WebView2 运行时，正在从微软官网下载安装……",
        "下载的 WebView2 安装程序没有微软的有效签名，已停止安装。",
        "WebView2 运行时安装失败（{0}）。",
        "正在卸载……",
        "已卸载。原来的旧版屏保（如果有）保存在 C:\\ProgramData\\DoraSaver\\original-backup。",
        "确定要卸载所有哆啦A梦屏保吗？",
        "请至少选择一个屏保和一种名字。",
        "  ⚠ {0}",
        "已卸载，但有 {0} 个文件被占用没能删除，重启电脑后可以手动删除。",
        "安装程序已经在运行了。",
        "出错了：{0}");

    public static SetupText Japanese { get; } = new(
        UiLanguage.Japanese,
        "Yu Gothic UI",
        "ドラえもんスクリーンセーバー復活計画 セットアップ",
        "インターネット・アーカイブ（Wayback Machine）から、ドラえもん公式サイトで当時無料配布されていたスクリーンセーバーの元ファイルをダウンロードし、このパソコン上でアニメーションを取り出して、オープンソースの Flash\u00A0エミュレーター Ruffle で再生します。本プログラムにドラえもんの素材は含まれていません。アニメーションの著作権は © 藤子プロ・小学館 ほかに帰属します。個人で楽しむ目的でお使いください。",
        "インストールするスクリーンセーバー",
        "スクリーンセーバー一覧での名前",
        "インストール",
        "アンインストール",
        "スクリーンセーバーの設定を開く",
        "閉じる",
        "キャンセル",
        "取得中：{0}（{1}年）",
        "  ✓ ダウンロードと検証が完了しました",
        "  ✓ 以前にインストールしたファイルをそのまま使います（検証済み）",
        "  ✗ 失敗：{0}",
        "  この元ファイルは古い形式のため、オープンソースの展開ツール unar（The Unarchiver）を追加でダウンロードします。",
        "元ファイルの中に、記録と一致するアニメーションが見つかりませんでした。",
        "インストールしています……",
        "スクリーンセーバーのファイルを {0} 個インストールしました。",
        "壊れた旧版をバックアップフォルダーに移動しました：{0}",
        "インストール完了！スクリーンセーバーは {0} 個です。「スクリーン セーバーの設定」から選べます。",
        "{0} 個をインストールしました。次の {1} 個はインストールできませんでした：{2}",
        "何もインストールされませんでした。",
        "使用中のスクリーンセーバーを新しいものに切り替えました：{0}",
        "Microsoft Edge WebView2 ランタイムが必要です。マイクロソフトの公式サイトからダウンロードしてインストールしています……",
        "ダウンロードした WebView2 インストーラーにマイクロソフトの有効な署名がないため、中止しました。",
        "WebView2 ランタイムをインストールできませんでした（{0}）。",
        "アンインストールしています……",
        "アンインストールしました。旧版（あった場合）は C:\\ProgramData\\DoraSaver\\original-backup に保存されています。",
        "ドラえもんのスクリーンセーバーをすべてアンインストールしますか？",
        "スクリーンセーバーと名前を少なくとも 1 つずつ選んでください。",
        "  ⚠ {0}",
        "アンインストールしましたが、使用中のため {0} 個のファイルを削除できませんでした。再起動後に手動で削除できます。",
        "セットアップはすでに実行中です。",
        "エラー：{0}");

    public static SetupText English { get; } = new(
        UiLanguage.English,
        "Segoe UI",
        "Doraemon Screensaver Revival Setup",
        "This setup downloads the original screensavers that the official Doraemon websites gave away in the 2000s from the Internet Archive (Wayback Machine), extracts the animations on your PC, and plays them with Ruffle, an open-source Flash emulator. No Doraemon assets are included in this program; the animations are © Fujiko-Pro, Shogakukan and others. For personal enjoyment only.",
        "Screensavers to install",
        "Names shown in the screensaver list",
        "Install",
        "Uninstall",
        "Open Screen Saver Settings",
        "Close",
        "Cancel",
        "Fetching: {0} ({1})",
        "  ✓ Downloaded and verified",
        "  ✓ Reusing the previously installed file (verified)",
        "  ✗ Failed: {0}",
        "  This original uses an old archive format, so the open-source unar tool (The Unarchiver) is downloaded as well.",
        "The original file does not contain the expected animation.",
        "Installing...",
        "Installed {0} screensaver files.",
        "Moved a broken old version to the backup folder: {0}",
        "Done! {0} screensavers installed. Pick one in Screen Saver Settings.",
        "Installed {0} screensavers. These {1} could not be installed: {2}",
        "Nothing was installed.",
        "Your active screensaver now uses the new version: {0}",
        "The Microsoft Edge WebView2 Runtime is required. Downloading it from Microsoft...",
        "The downloaded WebView2 installer is not validly signed by Microsoft, so setup stopped.",
        "Installing the WebView2 Runtime failed ({0}).",
        "Uninstalling...",
        "Uninstalled. Old versions (if any) are kept in C:\\ProgramData\\DoraSaver\\original-backup.",
        "Uninstall all Doraemon screensavers?",
        "Select at least one screensaver and one name language.",
        "  ⚠ {0}",
        "Uninstalled, but {0} files were in use and could not be deleted. You can delete them after restarting.",
        "Setup is already running.",
        "Error: {0}");

    public static SetupText For(UiLanguage language) => language switch
    {
        UiLanguage.Japanese => Japanese,
        UiLanguage.English => English,
        _ => Chinese,
    };

    public static UiLanguage Detect(CultureInfo culture) => culture.TwoLetterISOLanguageName switch
    {
        "zh" => UiLanguage.Chinese,
        "ja" => UiLanguage.Japanese,
        _ => UiLanguage.English,
    };
}
